name: reverie_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/reverie-logo.png  # Ensure this is SVG if the file is SVG, change to .png if it is PNG
    - assets/on-board-1.png
    - assets/on-board-2.png
    - assets/on-board-3.png
    - assets/on-board-4.png
    - assets/arrow.png
    - assets/sneakers.png
    - assets/jackets.png
    - assets/women.png
    - assets/men.png
    - assets/sweaters.png
    - assets/handbags.png
    - assets/kids.png
    - assets/shoes.png
    - assets/bags.png
    - assets/watches.png
    

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700